---
title: "Introduction"
author: "Adharsh Murali"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Installation

```{r eval=FALSE}

# install.packages("devtools")
library("devtools")
library("lubridate")
library("tidyverse")
library("wisard")
devtools::install_github("smeyer-umich/wisard", auth_token = "725cd269dcfd0b64fdeb5aa51a3e0a52193fdd3c")
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

temporal_file = file.path("Z://va_aki_project/datasets/check.csv")
fixed_file = file.path("Z://va_aki_project/datasets/fixed_data.csv")

```

# 1) Load in the fixed data and temporal data

```{r}
library(tidyverse, quietly = TRUE)




dev_data =  disk.frame::csv_to_disk.frame(infile = temporal_file,                                      
                                          outdir ="Z://va_aki_project/datasets/tmp",
                                          shardby = "encounter_id",
                                          backend = "data.table")

# The fixed data should of type tibble, data.frame or disk frame.
fixed_data = data.table::fread(fixed_file) %>% as_tibble()
fixed_data %>% head()

```

# 2) Creating a wizard object. 

```{r}
# input temporal_dataframe, fixed dataframe 
# return is a wizard object.

wizard_object = wisard::build_wizard_object(temporal_data = dev_data,
                            fixed_data = fixed_data) 
 
```

# 3) Generating the lagged predictors for the window size and lookback.

```{r}
#The input parameter are 
#1) wizard object,
#2) windowsize, 
#3) lookback,
#4) lookahead,
#5) step
#6) feature_stat
#7) impute 
# output is wizard object with updated wizard frame

wizard_object = wisard::add_lagged_predictors(obj = wizard_object,
                       window_size = list("meds" = lubridate::hours(6),"labs" = lubridate::hours(6)),
                       lookback = list("meds" =lubridate:: hours(6), labs = lubridate::hours(48)),
                       lookahead = lubridate::hours(30),
                       step = lubridate::hours(3),
                       feature_stat = list(labs = c('min', 'mean', 'max'),
                       meds = ('min')),
                       impute = F)
wizard_object$wizard_frame                 
```

# 4) Including the proportional and differential variation of lagged features.

```{r}
wizard_object  = wisard::add_prop_predictors(obj = wizard_object,categories = list("labs")) %>%
                  wisard::add_diff_predictors(categories = list("labs"))
wizard_object$wizard_frame
```

# 5) Generating the outcome features for analysis.

```{r}

wizard_object  = wisard::add_outcome(obj = wizard_object,outcome_var = "SBP",outcome_stat = list("mean")) 

wizard_object$wizard_frame
```

# 6) Finally writing the results to a disk frame object or file location

```{r}

wizard_object = wisard::write_to(obj = wizard_object,write_file = NULL,most_recent = T)

wizard_object$wizard_frame
```

